### ISSUE TITLE
Decryption not working

### ISSUE THREAD

**Issue by tayhoney82** [kevinychen/project-euler#1]
This is the output for OSX 10.13
I am getting the same error on windows and mingw w64

update answers.txt:
```
1. 233168
```

Then run:
```
bash scripts/setup.sh 
```

Applying auto-encrypt/decrypt filters...
Force rerunning git checkout to decrypt files...
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
140736046924672:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:
error: external filter './scripts/encrypt.sh -d' failed 1
error: external filter './scripts/encrypt.sh -d' failed
Done.

I am having hard time understanding you aes code .
can you just get it working online say here coderstool.com/aes-decryption
and share the link

**Comment by kevinychen** [comment]
Thanks for pointing this out.
